(********************************************************************
 * COPYRIGHT --  
 ********************************************************************
 * Program: traceConfig
 * File: traceConfigInit.st
 * Author: buchananw
 * Created: January 16, 2014
 ********************************************************************
 * Implementation of program traceConfig
 ********************************************************************)

PROGRAM _INIT


(* TODO : Add your code here *)


END_PROGRAM

